name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: unbuntu-latest
    steps:
      - name: https://github.com/MioLemon/actions-learning-pathway.git
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
